### ISSUE TITLE
Create a attached Document validation tool

### ISSUE THREAD

**Issue by tmccormi** [LibreHealthIO/LibreEHR#1011]
Administration tool that checks each document in 'document' table to see that it actually exists on disk Or in couchdb, if used) and the hash still matches.

Produces a browsable report.

**Comment by apooravc** [comment]
@tmccormi Working on it.

**Comment by sandipbhuyan** [comment]
@tmccormi  I want more specification about this issue.

**Comment by aethelwulffe** [comment]
There are also some issues for "moved" documents merely being set as URL strings in the database being changed instead of actually moving the files in the directory structure.  Frankly, I wish that the patient documents were directory structure based (parse the directory, use hashes for validation *and searches*).
