### ISSUE TITLE
Ray's Eye Form

### ISSUE THREAD

**Issue by teryhill** [LibreHealthIO/LibreEHR#314]
I have been working on bringing in Ray's Eye Form. This is a very large commit so I would like to bring it in as 2 chunks. First the assets that are needed and then the actual code. This will be as a loadable form.

**Comment by tmccormi** [comment]
Still seems like something that should be an "install if needed" module, not part of the base line for say, general practice, or mental health ....

**Comment by teryhill** [comment]
It will be just a form that can be added to interface/forms and loaded from there. We will need to test this on the various platforms. Has anyone created an uninstall script for an un-used form?

**Comment by tmccormi** [comment]
I'm sensitive about added assets that are only used by one thing ... code bloat is something we have been fighting ...

**Comment by teryhill** [comment]
I understand but some of the assets are 
jquery-ui-1-10-4
pure-0-5-0
bootstrap-3-3-4
qtip2-2-2-1
font-awesome-4-6-3

I am not sure how you are going to attract developers with out assets but you guys know more than I

**Comment by tmccormi** [comment]
This is a philosophy issue.   
1) YES we need to have good tools to work with, but you don't need to have every tool ever made to create a nice product
2) We just spent months removing code and overlapping tools.    

That said assets that are specific to a particular module should be installed with the module in some fashion, not just dumped into vendor directory.

So what I'm suggesting is that you create a package that is it's own repo (or part of a forms/modules repo) and a simple, maybe composer based installer for it.    That way if a Ophthalmologist needs that form it's a simple process that does not burden the main repository.

**Comment by tmccormi** [comment]
I'm not suggesting you close the issue...  It's a good form.  Post the code and let's if we can make a module out of it. We need a good candidate for this kind of thing

**Comment by aethelwulffe** [comment]
Here are my issues:
1.  We have not actually cleaned up assets yet.  The jquery attempt is currently a failure for a reason I cannot fathom.
2.  The TAGS stuff came in with another set of dependencies...without protest.  This includes the bootstrap bit.  If the idea is to locate, name, and contain dependencies in separate directories, that is fine, but we should not turn a blank eye to it when it is for someone in Ireland.
3.  If each "module" or self contained bit of code has it's own dependencies with it, then we don't worry about having 15 sets of the bootstrap code or whatever everywhere, because those are all optional directories with hooks in the code, and configurations that say if they exist or not.  In that case, this code need have nothing more than an official place for it to live.
4.  If this is an eye form, and it is contained in FORMS, then it is already a sort of module, if not living in that composer command line stuff that most of us don't know how to implement.  In that case, perhaps it should go into a forms repo, and that would be fine.  We could even make windows installers for the forms for those systems, and something involving a lot of typing for the Linux distros.  In that case, the "module" has it's own copy of the dependencies it needs, which are maintained or intentionally left static as required.

If we were in control of dependencies, then I would say you always call the library from the correct location.  We don't have that, and this idea only seems popular in some instances, as code that violates that seems to be getting merged up.  Two options:

- [ ] Everything becomes completely self contained, with everything in it's own directory, NOT touching the INTERFACE or LIBRARIES directories at all save for hooks.  Everything goes into "MODULES"under root...not the dumb-ass name "VENDOR" buried elsewhere.
- [ ] Everything that is an off-the-shelf library, font, css, pic, or any of that crap goes in ONE directory structure per, ONlY the custom built code goes into a MODULE, and nothing that violates that comes into the code base...and we work hard to get to that model right here and now.

Let's pick one.  Now.

**Comment by aethelwulffe** [comment]
In addition, I am totally sick of having a total dearth of decent-looking and operating forms available as a standard option, and I hate most of the forms and reports that exist right now.  Let's do a trade-off.  We delete one for each that we add.  No, I don't want the contribs directory bloated up again, and I don't want the specialist forms in as "standard".  I want most all of them gone, only really nice ones left for GP use, and I want a repo...now...for forms and reports.

**Comment by tmccormi** [comment]
The TAGS stuff was not for Ireland, that stuff was created for OpenEMR and submitted to OpenEMR before LibreEHR existed...

But in general I agree with the whole rant :-)

**Comment by teryhill** [comment]
So does this mean we need to have multiple copies of say bootstrap in 10 different directories, Not what I think the intention should be. It should be contained in a central directory and maintained there. If a newer version of the asset is used then the other usage is located in the code and upgraded to the newer version

Am I missing the Idea?

**Comment by tmccormi** [comment]
I think this is general conversation that should be moved to the forum or at least a new ISSUE tagged as a discussion.

**Comment by tmccormi** [comment]
See #323

**Comment by aethelwulffe** [comment]
I am closing this issue, but referencing the eye form in a new issue.
