### ISSUE TITLE
tags need to have collapse and expand on the demographics page

### ISSUE THREAD

**Issue by teryhill** [LibreHealthIO/LibreEHR#405]
tags need to have collapse and expand on the demographics page. this will maintain the current look, all others have the collapse and expand dialog . @ken

**Comment by azwreith** [comment]
Hi, I'm Ujjwal!
I'd like to take up this issue c:

**Comment by teryhill** [comment]
@azwreith go ahead. Look at the code for the expand and collapse of the other items that is the pattern to follow.

**Comment by aethelwulffe** [comment]
Lemme know what help you may need getting started and all that Ujiwal.  Some folks are having issues with server defaults when doing setup.
...of course you might go a long way with this issue without ever seeing it run in the application!

**Comment by azwreith** [comment]
Hi @aethelwulffe, thank you! Yes, I encountered rough seas as well while trying to setup: Errors due to the xml php module not being installed. And new version of MySQL has strict mode enabled by default so it wasn't letting some of the tables to be created. Maybe we can update the installation guide to have a FAQ or Troubleshooting section ツ

**Comment by teryhill** [comment]
The code tests great. @kchapple will need to look at it since tags is his

**Comment by aethelwulffe** [comment]
Ujjwal, I think we have to get the install docs posted nice and obvious very very soon.  I am trying to get the xampp pack put into the bintray right now, but those additional install docs are real important.

**Comment by azwreith** [comment]
@aethelwulffe Yes, I agree. I'll add installation instructions for linux and some of the issues encountered to #446. Thanks!
