### ISSUE TITLE
Possable projects for GSOC

### ISSUE THREAD

**Issue by teryhill** [LibreHealthIO/LibreEHR#433]
Here are some Ideas on what we could have them do that would be easy and get them into the code.

- [ ] Checks on Date of Birth to not allow future dates.
- [ ] Checks on Date of Death to not allow future dates.
- [ ] Phone number formatting in demographics (123)456-7890.
- [ ] Change statement to allow selection of no printing if patient is deceased.
- [ ] Add checks on Miscellaneous Billing Form to allow only one copy of the form per encounter.
- [ ] A report listing the top ten (or any number selected) CPT or ICD10 codes for a time frame.
- [ ] A report listing adjustment codes and the dollar amount of the selected codes.
- [ ] Add a "Back to Patient" on the reports on the demographics screen.
- [ ] Create a 'on demand' receipt that can be printed for a patient at any time.
- [ ] Installation instructions for different OS's

**Comment by robbyoconnor** [comment]
Please split these up @teryhill

**Comment by aethelwulffe** [comment]
Robby,
This is obviously a checklist for creating quality issue tickets.  As they are "split up" they will be checked off the list, or added to it.  You will note that it is named "Possiable", not "Possible".  That indicates this is for the whole Posse to work on (with an 'i' and not an 'e', indicating proper form for a _group_ of the individual unit know as a "posse"...like "octopi") Otherwise, they would be "indiviudable".  ;)

**Comment by teryhill** [comment]
Yezz Louise

**Comment by teryhill** [comment]
They have been rode down and broke up
