### ISSUE TITLE
Bug in SOAP and ROS Form Smarty Templates

### ISSUE THREAD

**Issue by yehster** [LibreHealthIO/LibreEHR#591]
Here is the commit to correct the problem found.

https://github.com/yehster/LibreEHR/commit/f46eefb0d06f71efdd2a664d7099a8853c1bd9fd

As mentioned in the commit, the > which is meant to be to close an HTML tag is actually being processed as PHP and a floating "greater than" which causes a syntax error.

Try to load either of these two forms at present it fails, with an error reported in the log.

**Comment by yehster** [comment]
@teryhill Please review

**Comment by aethelwulffe** [comment]
https://github.com/LibreHealthIO/LibreEHR/issues/553
For reference.

**Comment by aethelwulffe** [comment]
We need a quick replacement for the smarty-template based SOAP note for the educational demo they are working on.  It is basically four text boxes.  I imagine this is needed because someone has migrated data to the SOAP form.  If that is not the case, then we DON'T need a 1:1 replacement...we just need to uninstall the form on the demo.

**Comment by teryhill** [comment]
@aethelwulffe Can you review this ?

**Comment by aethelwulffe** [comment]
Please put in a PR to master here...

**Comment by teryhill** [comment]
File merged Closing this issue
