### ISSUE TITLE
Report Malfunctions

### ISSUE THREAD

**Issue by rehoyt** [LibreHealthIO/LibreEHR#618]
Going through all of the Client and Clinic reports, from what I can tell the appointments, encounters, CQMs, Standardized reports and syndromic surveillance reports are not functional. I'm in the process of creating the user guide and screen shots so need to know what is possible and what is not

**Comment by teryhill** [comment]
These work for me on my system:
![repappt](https://user-images.githubusercontent.com/4655366/28132963-675e7c48-670c-11e7-9914-860498e0bc90.JPG)
![repcqm](https://user-images.githubusercontent.com/4655366/28132965-69cb916e-670c-11e7-8af4-b89925d6e02a.JPG)
![repencounter](https://user-images.githubusercontent.com/4655366/28132976-6fc43d28-670c-11e7-9b1e-3af2094d5748.JPG)

I am not sure what the standardized reports are.  I do not know if I have data on my system to support the syndromic surveillance report but the report did run. I did not have any issues running the reports listed With the exception of not knowing what you were referencing as the standardized reports.

**Comment by rehoyt** [comment]
I saw the header in several instances but no content below it. My Internet has been slow so perhaps it is getting timed out with long reports. I'll try later today and see if I can see them. Thanks

**Comment by rehoyt** [comment]
I am seeing the encounter and appointment report results. The CQMs is trying to download something on all patients so slow. The standardized reports report active/passive alerts and patient reminder stats. That is not very important, but as stated earlier, searching for lab results is important

**Comment by aethelwulffe** [comment]
Yeah, the report system (vanilla) is terrible slow and poorly implemented.

**Comment by teryhill** [comment]
@rehoyt  is this issue completed?

**Comment by rehoyt** [comment]
I need to see if I can create any type of simple CQM. This morning I used the same search criteria and after three minutes it is still spinning and saying 0/9365 so no reports generated after three minutes

**Comment by aethelwulffe** [comment]
Well, after yesterday's meeting with my company's supposed backers and partners, I will be discussing the release of our reporting and analysis system to the project with my partner.  It processes a year's worth of 10,000 patients over ~250 measure sets in about four minutes.  We also have a better structure and more optimized...everything...that should help you create new measure sets trivially.  This is supposing that I get the go-ahead on releasing all this for good-will sake instead of actually earning our living off of it.  At this point, I actually hope that is the case.
  Either way, I am going to trickle some stuff in.  I ported the system (rough draft round 1) to LibreHealthEHR from a 4.x OEMR version, and put up the branch on our repo about 36 hours ago.  We should be able to have that for testing pretty quick here.  In any case, if we get a dump of the NANES data (which is no-where nearly as extensive as our current test data) we can add that to one of our demo, test or development servers, where you folks can play with it.  You could probably play inside the demo right now (for the current stable version).
  Honestly, the Standard, AMC and CQM/PQRI measures that exist are...very poor quality.  They are also years and years out of date.  Our current version is for MIPS/MACRA 2017, Registry stuff, and for ACO's.  That doesn't mean that the code cares WHAT you put in a new measure you create though.

**Comment by rehoyt** [comment]
That sounds extremely interesting and I wonder if this type of data would appeal to a new healthcare audience, like quality managers, MHA grads and so forth

**Comment by aethelwulffe** [comment]
Well, it is the regulatory QA standard here in the U.S.  I rather imagine it means that releasing the code will put a huge hurting on companies that specialize in regulatory compliance, like Mingle.com etc...  I ain't against that.  The important thing (to you) is that it can drive an engine that uses algorithms against a standardized data type, allows you to save those algorithms in a mix-and-match way, selecting different sets of them as you desire.   You can export the results in many ways, calculate incremental progression of your results against a data set, combine or name your saved reports, add amplifying data to patients in the context of a base report, and a lot of other interesting things.
  The problem in the existing CQM reports (other than not being very scalable, handy, complete, pertinent etc...) is not with the base engine (which was needlessly messy and complex) but that the actual measures and rules try to solve the problems in the wrong way.
  The EHR doesn't need to have a home-rolled version of phpmyadmin to do this job.  It just needs to do the job.

**Comment by teryhill** [comment]
Not to be a pest but @rehoyt is this issue completed? 

If there is some thing here that is keeping it open that is not related to the issue title please make a new issue for it so it can be easily followed.

**Comment by rehoyt** [comment]
You can close it but tell me why your CQM report only shows 8 patients. When I input the same parameters it tries to give me reports on 9600 patients and therefore takes forever. Thanks

**Comment by teryhill** [comment]
@rehoyt  I am sorry you are having issues with the CQM report on the LibreHealth EHR system. I am just a developer who donates my time to the project. I believe that @aethelwulffe  or @tmccormi  would have better answers than I do.

**Comment by aethelwulffe** [comment]
@rhoyt  With the new MIPS stuff coming in, the CQM report itself is going away in favor of something...better...that will allow you to run those 9600 patients against reports with better facility.  It will also mean that your test data will require some transformations to make it useful for reporting.
