### ISSUE TITLE
INNODB server variables setup recommendations.

### ISSUE THREAD

**Issue by aethelwulffe** [LibreHealthIO/LibreEHR#707]
Recently posted this:  https://mariadb.com/kb/en/library/converting-tables-from-myisam-to-innodb/

There is a lot of good advice on table conversion, and a lot of points made concerning "gotchas" we experienced, as well as how to avoid those.  At this time, the server variable recommendations we make in the setup are not appropriate for running the INNODB engine.  Memory is handled very differently in INNODB vs MyISAM.  Many of the "silent fails" we have seen on setup are due to insufficient settings for a production instance.  Apache has hilariously conservative default settings.
  Of immediate note:
    key_buffer_size — small but non-zero; say, 10M;
    innodb_buffer_pool_size — 70% of available RAM

**Comment by tmccormi** [comment]
I'll update the setup notes.

**Comment by tmccormi** [comment]
added this:
Configuration of PHP...

We recommend making the following changes to your PHP installation, which can normally be done by editing the php.ini configuration file:

Your php.ini file can be found at /etc/php5/apache2/php.ini

To ensure proper functioning of LibreHealth EHR you must make sure that settings in php.ini file include:

- "short_open_tag = On"
- "display_errors = Off"
- "register_globals = Off"
- "max_execution_time" set to at least 60
- "max_input_time" set to at least 90
- "post_max_size" set to at least 30M
- "memory_limit" set to at least "128M"
- "key_buffer_size" set to 10M
- "innodb_buffer_pool_size" set to 70% of available RAM.

In order to take full advantage of the patient documents capability you must make sure that settings in php.ini file include:

- "file_uploads = On"
- "upload_max_filesize" is appropriate for your use (32M seems good)
- "upload_tmp_dir" is set to a correct value that will work on your system.

**Comment by aethelwulffe** [comment]
We should include (in docs) recommendations for TEMPORARY settings and for DEVELOPER settings for things like large database imports, conversions, running super-huge reports and the like.
Personally, I think that system percentages are better recommendations a lot of the time.

Another one of my favorite textbytes for server-side stuff:
http://www.bigeng.io/php-memory-optimization/
These nice little functions figured out (over a couple of weeks) that for the ARSP clinic, we were better off (calculated exacts) with
 max_execution_time =122
max_inpute_time = 160
post_max_size = 52M
memory_limit = 512M 
...that is/was running OEMR 4.2 on a single core (all it could use) with total system memory of 8GB.
Things have changed between these versions obviously.  More to the point, with 100 Maxclients  would require about 50GB of memory if everything were maxed out.  That is obviously not reasonable for the system.  On the other hand, setting it low kind of kills the type of work done by billers and supervisors (not anyone else).  The important factor is that some processes would occasionally run out of memory (like the damn logs).
  My proposed solution is to make one of the "advanced" summer of code projects be analysis of the memory usage of the system.
  The results of a study on a real in-use system could be used not so much in making the setup recommendations, but more for figuring out where the problems are and fixing those.
  I think a nice little js box somewhere (configurable) that shows updated results from functions found here:  http://php.net/manual/en/function.memory-get-usage.php  would be a nice little project possibly within reach of a student.

**Comment by tmccormi** [comment]
Closing this for the release 2.
