### ISSUE TITLE
Missing image on Install document

### ISSUE THREAD

**Issue by tmccormi** [LibreHealthIO/LibreEHR#709]
Document references:
 ... Documentation/1_Installing/images/1_install/**installer2.png**

Current List of files in repo.
**Documentation/1_Installing/images/1_install$ ls
installer10.png  installer3.png  installer5.png  installer7.png  installer9.png
installer1.png   installer4.png  installer6.png  installer8.png**

**Comment by tmccormi** [comment]
Anyone have any idea were this doc came from and where the missing image might be? @aethelwulffe @teryhill

**Comment by aethelwulffe** [comment]
Pretty sure that is all me.
I will check it out.

**Comment by aethelwulffe** [comment]
These were in the old repo as documentation resources.  It is missing the file.  I will look at old builds (all that exist) of the xampp installer to see if I can find the image.

**Comment by aethelwulffe** [comment]
Yeah, these were for the original installer I wrote...meant to be accessed by the installer when you run the .exe.  Any copies I had of that image are bound up in a saved  copy of that .exe.  Does not really matter.  They are all out-dated.  They should also (in the docs tree) be names something related to windows or xampp installer.
  I still have the scripts for inno Setup to compile builds.  Since I could never get distro on the LH resources, I am pretty sure I could host them on the HoneyPot server, and set it up to do a new build version every day if the diff is triggered..

**Comment by aethelwulffe** [comment]
This issue is resolved.
