### ISSUE TITLE
Global menu theme not functional

### ISSUE THREAD

**Issue by Trodrige** [LibreHealthIO/LibreEHR#749]
Appearance doesn't change even when either full or compact theme is selected. This functionality needs to be implemented.

**Comment by teryhill** [comment]
change the Theme to light and see if it works with it.

**Comment by Trodrige** [comment]
It doesn't work here. What do you observe @teryhill ?

**Comment by teryhill** [comment]
Not working for me either.

**Comment by Trodrige** [comment]
I'm a PHP guy, but I can't help noticing lots of issues on EHR UI. I'll create a new thread to talk about this generally. I'll come up with different issues for the UI that I've noticed, and ask others to add. It is a mini-project I'm taking up, attempting to create better UI while implementing Bootstrap.
I'll create the thread and layout all the task I'll be doing and call on the other EHR guys add what they think. @teryhill what do you think?

**Comment by teryhill** [comment]
Reach out to @nileshprasad137  He has done work on the UI already. I think it is a good project to get others involved in this.

**Comment by Trodrige** [comment]
Ok, 
1. I'll discuss with @nileshprasad137 
2. create the thread
3. lay down issues I've observed with the UI 
4. call on others to add their own observations and how they can be corrected.
5. call for volunteers to join me on this.

**Comment by nileshprasad137** [comment]
@Trodrige  My GSoC project was to remove Smarty Template Engine from the project and to improve User Interface. Removing Template Engine itself took half of the period , so in the remaining time, I tried to work on UI as much as possible. But these days, I am finding it difficult to continue contributing to UI because of academics and also because I am more into learning data analytics and backend.  

I would say this is a much larger mini project. As you might have noticed, the logic and design is interwined at several places throughout the project. This makes it difficult to use the full power of Bootstrap. It would really require a lot of changes to use Bootstrap fully. It would be great if you could help getting more volunteers to work over UI.

**Comment by Trodrige** [comment]
Thanks, @nileshprasad137. I'm trying to go through the project and come up with some tasks. Then I'll get a team of volunteers to work with. I'm also a backend guy, but I like seeing attractive and consistent stuff.
We'll be reaching to you often since you have some experience with UI already.
 Thanks again.

**Comment by teryhill** [comment]
@Trodrige The issue with the compactt and full theme not working is the code is missing from /interface/main/tabs/main.php after this line (line 54 in my version) <link rel="stylesheet" type="text/css" href="css/tabs.css"/> Place this line <link rel="stylesheet" type="text/css" href="../../themes/tabs_style_compact.css"/>

This causes a huge issue with the system as you will be able to see.

**Comment by aethelwulffe** [comment]
Triple verifying that this does not work.  I am not sure it ever worked...

**Comment by teryhill** [comment]
Dead issue will remove the options from globals
