### ISSUE TITLE
Inconsistent use of the term "Issues" -vs- "Medical Problems

### ISSUE THREAD

**Issue by tmccormi** [LibreHealthIO/LibreEHR#917]
Not sure how to resolve this, but if you click on the 'Issues' Link in the Patient Demographics you get this, labeled "Medical Problems" Which we all refer to as "Issues":

![issues-link-from-demog](https://user-images.githubusercontent.com/285835/34590444-b1fafd50-f16b-11e7-9890-2aa876f49464.png)

If you click on the Popup->Issues link you get this, which is used to review the links between "Issues" and Encounters.

![issues-links-to-diff-pages](https://user-images.githubusercontent.com/285835/34590500-0469c6fc-f16c-11e7-9e9c-56aab0b6d2ca.png)

**Comment by aethelwulffe** [comment]
The issues issue has been an issue since the day this was issued.
There is also overlap in the area of "History".

My suggestion from about 10 years ago (11?) was to change everything to "Health Factors".
with the following category names:

Diagnosis (INCLUDES Dental and Mental Health.  Both are covered by ICD codes.  There is no distinction in the difference!)

Allergies (same as above, should include the diagnosis, but this is a difference with a distinction).

Medications

Surgical Outcomes (Might be Treatment History for surgical or any other currently relevant past outcome factors).

-we should get clinical opinions of the above.

**Comment by tmccormi** [comment]
I think we could start with a simple renaming of the visual elements and move on to a better model after that.

**Comment by supernour09** [comment]
hi everyone so i was wondering if i want to fix this issues what is need just rename

**Comment by Janaki123456** [comment]
can u assign me
 this task

**Comment by Jdew192837** [comment]
@tmccormi @aethelwulffe @teryhill 
Could you all assign @ajeyprasand this issue?
